### ISSUE TITLE
Add fish food for kube-fzf

### ISSUE THREAD

**Issue by karuppiah7890** [thecasualcoder/fish-food#1]
I'll raise a PR for this

**Comment by karuppiah7890** [comment]
I have created the repo - https://github.com/karuppiah7890/thecasualcoder-fish-food . Not able to create PR as this repo is empty.

Also, the repo was made by checking https://github.com/fishworks/fish-food . It has circle ci tests for checking installation in ubuntu. I'll see if we can add windows tests too

**Comment by jskswamy** [comment]
@karuppiah7890 I've added `contribution.md` file and made a first commit, please raise a PR
